name: Psalm Security Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  psalm:
    name: Run Psalm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Download Psalm
        run: |
          curl -L https://github.com/vimeo/psalm/releases/latest/download/psalm.phar -o psalm.phar
          chmod +x psalm.phar

      - name: Run Psalm scan
        run: |
          php psalm.phar --output-format=console

      # Optional: generate SARIF output for GitHub Advanced Security Code Scanning
      - name: Run Psalm (SARIF Output)
        run: php psalm.phar --output-format=sarif > psalm-results.sarif

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: psalm-results.sarif
          category: psalm-security
